### ISSUE TITLE
エラー：　プラグイン「 mod_kakiemon 」に問題がある....と表示されます

### ISSUE THREAD

**Issue by nwtgck** [VERSION2-Inc/moodle-mod_kakiemon#1]
Moodle3.0を利用しています。
「一筆柿右衛門」を以下のコマンドを使ってダウンロードして、

``` sh
$ cd /var/www/html/moodle/mod/
$ git clone https://github.com/VERSION2-Inc/moodle-mod_kakiemon kakiemon
```

ダウンロード後にのページをリロードすると以下の画像のようになり
![2016-04-04 9 15 27](https://cloud.githubusercontent.com/assets/10933561/14235896/fce71084-fa45-11e5-8a4e-2fdd6b770ebb.png)

上の画像の[Moodleデータベースを更新する]を押すと以下の画像になります
![2016-04-03 15 56 13](https://cloud.githubusercontent.com/assets/10933561/14231174/9e5fdb22-f9b4-11e5-918e-f318a1e6233b.png)

> 申し訳ございません、プラグイン「mod_kakiemon」に問題がある、または古いため継続できません。

とエラーになっているようです

「一筆柿右衛門」をぜひ活用したいのです。どうしたらよいでしょうか？

**Comment by yama-ver2** [comment]
ご報告ありがとうございます。
ひとまずMoodle 3.0でインストールができるよう修正しました。

**Comment by nwtgck** [comment]
こちらの環境でもインストールが無事にできました。
新年度のご多用の中、迅速なご対応ありがとうございます
